create table if not exists public.devotionals (
  id bigint generated by default as identity primary key,
  date date not null unique,
  title text not null,
  scripture jsonb not null,
  message text not null,
  prayer_points jsonb not null default '[]'::jsonb,
  declarations jsonb not null default '[]'::jsonb,
  author text not null default 'Moses Afolabi',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_devotionals_date_desc
  on public.devotionals (date desc);

create or replace function public.set_devotionals_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_devotionals_updated_at on public.devotionals;
create trigger trg_devotionals_updated_at
before update on public.devotionals
for each row
execute function public.set_devotionals_updated_at();
